# Generated by Django 6.1.1 on 2026-09-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('F', 'Finalizado'), ('C', 'Criado'), ('E', 'Enviado'), ('P', 'Pendente'), ('R', 'Reprovado')], default='C', max_length=1),
        ),
    ]
