# Generated by Django 6.1.1 on 2026-09-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('R', 'Reprovado'), ('C', 'Criado'), ('A', 'Aprovado'), ('F', 'Finalizado'), ('E', 'Enviado'), ('P', 'Pendente')], default='C', max_length=1),
        ),
    ]
