# Generated by Django 6.1.1 on 2026-09-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('E', 'Enviado'), ('P', 'Pendente'), ('F', 'Finalizado'), ('R', 'Reprovado'), ('C', 'Criado')], default='C', max_length=1),
        ),
    ]
