# Generated by Django 6.1.1 on 2026-09-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('C', 'Criado'), ('F', 'Finalizado'), ('R', 'Reprovado'), ('E', 'Enviado')], default='C', max_length=1),
        ),
    ]
