# Generated by Django 6.1.1 on 2026-09-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('R', 'Reprovado'), ('P', 'Pendente'), ('A', 'Aprovado'), ('E', 'Enviado'), ('F', 'Finalizado'), ('C', 'Criado')], default='C', max_length=1),
        ),
    ]
