# Generated by Django 6.1.1 on 2026-09-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0010_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('C', 'Criado'), ('P', 'Pendente'), ('A', 'Aprovado'), ('E', 'Enviado'), ('R', 'Reprovado'), ('F', 'Finalizado')], default='C', max_length=1),
        ),
    ]
