# Generated by Django 6.1.1 on 2026-09-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0011_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('E', 'Enviado'), ('R', 'Reprovado'), ('C', 'Criado'), ('F', 'Finalizado'), ('P', 'Pendente'), ('A', 'Aprovado')], default='C', max_length=1),
        ),
    ]
