# Generated by Django 6.1.1 on 2026-09-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0013_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('C', 'Criado'), ('E', 'Enviado'), ('P', 'Pendente'), ('F', 'Finalizado'), ('R', 'Reprovado')], default='C', max_length=1),
        ),
    ]
