# Generated by Django 6.1.1 on 2026-09-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0014_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('A', 'Aprovado'), ('E', 'Enviado'), ('R', 'Reprovado'), ('C', 'Criado')], default='C', max_length=1),
        ),
    ]
