# Generated by Django 6.1.1 on 2026-09-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0015_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('F', 'Finalizado'), ('E', 'Enviado'), ('P', 'Pendente'), ('R', 'Reprovado'), ('C', 'Criado'), ('A', 'Aprovado')], default='C', max_length=1),
        ),
    ]
