# Generated by Django 6.1.1 on 2026-09-26 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco_marketing',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_marketing_promocional',
        ),
    ]
